server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://etrade-pg-auth:5432/etrade_auth_db
    username: ${DB_USERNAME:etrade_user}
    password: ${DB_PASSWORD:etrade_pass}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://etrade-keycloak:8080}
  realm: ${KEYCLOAK_REALM:etrade}
  client-id: ${KEYCLOAK_CLIENT_ID:etrade-backend}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-admin:eureka-pass@etrade-discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    ma.portnet: DEBUG
    org.springframework.security: INFO